#!/usr/local/bin/bash

set -e

# TODO: accept a parameter; accept multiple parameters too?
# See https://stackoverflow.com/a/38558776/26702
fswatch -0 "${@/%/.tex}" plato.bib | xargs -0 -I {} make "$@"
